import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#b6c4ff',
        'surface-variant': '#2d3449',
        'surface-container-lowest': '#060e20',
        'primary-fixed': '#dce1ff',
        'inverse-on-surface': '#283044',
        'on-tertiary-fixed-variant': '#004f58',
        'on-tertiary-container': '#e6fbff',
        'on-secondary-fixed-variant': '#4f00d0',
        'error-container': '#93000a',
        'tertiary-fixed': '#9cf0ff',
        'surface-container-high': '#222a3d',
        'primary-fixed-dim': '#b6c4ff',
        'error': '#ffb4ab',
        'on-surface': '#dae2fd',
        'on-tertiary-fixed': '#001f24',
        'surface-container-low': '#131b2e',
        'on-primary-fixed': '#001550',
        'on-secondary-fixed': '#20005f',
        'surface': '#0b1326',
        'on-background': '#dae2fd',
        'surface-bright': '#31394d',
        'on-secondary-container': '#c0acff',
        'on-error-container': '#ffdad6',
        'tertiary': '#00daf3',
        'on-primary': '#002780',
        'tertiary-fixed-dim': '#00daf3',
        'primary': '#b6c4ff',
        'outline-variant': '#434656',
        'on-surface-variant': '#c3c5d8',
        'inverse-surface': '#dae2fd',
        'secondary-container': '#5203d5',
        'on-primary-container': '#f7f5ff',
        'surface-container-highest': '#2d3449',
        'surface-dim': '#0b1326',
        'on-tertiary': '#00363d',
        'background': '#0b1326',
        'surface-container': '#171f33',
        'on-secondary': '#370096',
        'secondary': '#cdbdff',
        'secondary-fixed': '#e8deff',
        'primary-container': '#2962ff',
        'outline': '#8d90a2',
        'on-error': '#690005',
        'inverse-primary': '#004ee8',
        'secondary-fixed-dim': '#cdbdff',
        'tertiary-container': '#007d8c',
        'on-primary-fixed-variant': '#003ab3'
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'margin_safe': '32px',
        'grid_columns': '12',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'base': '4px',
        'gutter': '24px',
        'xs': '4px',
        'xl': '40px',
      },
      fontFamily: {
        'body-main': ['Inter', 'sans-serif'],
        'heading': ['Playfair Display', 'serif'],
        'code-snippet': ['Space Grotesk', 'monospace'],
        'mono-label': ['Space Grotesk', 'sans-serif']
      },
      fontSize: {
        'mono-label': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        'code-snippet': ['13px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-main': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'h3': ['24px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'h2': ['30px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h1': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}

export default config
